# Generated by Django 5.2.8 on 2026-01-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="truck",
            old_name="current_latitude",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="truck",
            old_name="current_longitude",
            new_name="longitude",
        ),
        migrations.AddField(
            model_name="truck",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="truck",
            name="license_plate",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
