# Generated by Django 5.2.8 on 2026-01-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_rename_current_latitude_truck_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="truck",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
