# Generated by Django 5.2.8 on 2026-02-14 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0003_truck_is_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="assigned_truck",
        ),
        migrations.AddField(
            model_name="driver",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("en_route", "En route"),
                    ("off_duty", "Off duty"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="truck",
            name="driver",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="truck",
                to="drivers.driver",
            ),
        ),
        migrations.AddField(
            model_name="truck",
            name="status",
            field=models.CharField(default="available", max_length=20),
        ),
    ]
