# Generated by Django 5.2.8 on 2026-02-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0004_remove_driver_assigned_truck_driver_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="truck",
            name="is_available",
        ),
    ]
