# Generated by Django 5.2.8 on 2026-02-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0005_remove_truck_is_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="truck",
            name="status",
        ),
        migrations.AlterField(
            model_name="truck",
            name="license_plate",
            field=models.CharField(max_length=20),
        ),
    ]
