# Generated by Django 5.2.8 on 2026-01-20 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_rename_current_latitude_truck_latitude_and_more"),
        ("pickups", "0001_initial"),
        ("routing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="assigned_truck",
        ),
        migrations.AlterField(
            model_name="route",
            name="truck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="drivers.truck"
            ),
        ),
        migrations.DeleteModel(
            name="WastePickupRequest",
        ),
        migrations.AlterField(
            model_name="route",
            name="pickups",
            field=models.ManyToManyField(to="pickups.wastepickuprequest"),
        ),
        migrations.DeleteModel(
            name="Driver",
        ),
        migrations.DeleteModel(
            name="Truck",
        ),
    ]
