# Generated by Django 5.2.8 on 2026-01-21 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0003_truck_is_available"),
        ("pickups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wastepickuprequest",
            name="assigned_truck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="drivers.truck",
            ),
        ),
        migrations.AlterField(
            model_name="wastepickuprequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("collected", "Collected"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
