# Generated by Django 5.2.8 on 2026-02-04 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0003_truck_is_available"),
        ("pickups", "0002_wastepickuprequest_assigned_truck_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wastepickuprequest",
            name="assigned_truck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pickups",
                to="drivers.truck",
            ),
        ),
    ]
